---
openapi: 3.0.0
info:
  title: Hola Mundo Dtic
  description: Esto es un Hola Mundo
  contact:
    email: info@dtic.org
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/SIG4/HolaMundo/1.0.0
  description: SwaggerHub API Auto Mocking
- url: http://dtic.org/HolaMundo/1.0.0
  description: Servidor Apis DTIC
tags:
- name: tag hola mundo dtic
  description: Desarrollado en dtic.ua.es
paths:
  /holamundo:
    get:
      description: GET Hola Mundo
      parameters:
      - name: nombre Hola Mundo
        in: query
        description: nombre Hola Mundo
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: Hola Mundo Correcto
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "400":
          description: Hola Mundo Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_400'
    post:
      description: POST Hola Mundo
      parameters:
      - name: nombre Hola Mundo
        in: query
        description: nombre Hola Mundo
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: Hola Mundo POSTCorrecto
        "400":
          description: Hola Mundo Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_400'
components:
  schemas:
    inline_response_200:
      type: object
      properties:
        nombre:
          type: string
        contador:
          type: integer
    inline_response_400:
      type: object
      properties:
        message:
          type: string
