openapi: "3.0.0"
info:
  title: OpenAPI
  description: MTIS Practica 2 OpenAPI
  version: 1.0.0
servers:
  - url: http://localhost:8000/
    description: Local server
    
tags:
  - name: Sala
    description: Peticiones relacionadas con Salas
  - name: Nivel
    description: Peticiones relacionadas con Niveles
  - name: Dispositivo
    description: Peticiones relacionadas con Dispositivos
  - name: Notificacion
    description: Peticiones relacionadas con Notificaciones
    
paths:
  /salas:
    post:
      tags:
        - Sala
      summary: Crea una nueva sala en la base de datos
      requestBody:
        description: Estructura que define una sala
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Sala"
      responses:
        '200':
          description: Sala creada exitosamente
        '400':
          description: Error al crear la sala

  /salas/{codigoSala}:
    delete:
      tags:
        - Sala
      summary: Borra una sala de la base de datos
      parameters:
        - in: path
          name: codigoSala
          schema:
            type: integer
          required: true
          description: Código de la sala a borrar
      responses:
        '200':
          description: Sala borrada exitosamente
        '400':
          description: Error al borrar la sala
    put:
      tags:
        - Sala
      summary: Actualiza una sala en la base de datos
      parameters:
        - in: path
          name: codigoSala
          schema:
            type: integer
          required: true
          description: Código de la sala a modificar
      requestBody:
        description: Estructura completa que define una sala
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Sala"
      responses:
        '200':
          description: Sala actualizada exitosamente
        '400':
          description: Error al actualizar la sala
    get:
      tags:
        - Sala
      summary: Obtiene la estructura completa de una sala
      parameters:
        - in: path
          name: codigoSala
          schema:
            type: integer
          required: true
          description: Código de la sala a consultar
      responses:
        '200':
          description: Sala encontrada exitosamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Sala"
        '404':
          description: Sala no encontrada en la base de datos
          
  /niveles:
    post:
      tags:
        - Nivel
      summary: Crea un nuevo nivel en BD
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Nivel'
      responses:
        '200':
          description: OK
        '400':
          description: Petición incorrecta
    
  /niveles/{nivel}:
    delete:
      tags:
        - Nivel
      summary: Elimina un nivel de BD
      parameters:
        - in: path
          name: nivel
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
        '404':
          description: Nivel no encontrado
    put:
      tags:
      - Nivel
      summary: Actualiza un nivel en BD
      parameters:
        - in: path
          name: nivel
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Nivel'
      responses:
        '200':
          description: OK
        '400':
          description: Petición incorrecta
        '404':
          description: Nivel no encontrado
    get:
      tags:
        - Nivel
      summary: Devuelve información de un nivel
      parameters:
        - in: path
          name: nivel
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Nivel'
        '404':
          description: Nivel no encontrado
          
  /dispositivos:
    post:
      tags:
        - Dispositivo
      summary: Crea un nuevo dispositivo en BD
      description: Crea un nuevo dispositivo en BD a partir de la estructura indicada en BD
      requestBody:
        description: Estructura que define un dispositivo
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Dispositivo"
      responses:
        "201":
          description: Creado exitosamente
        "400":
          description: Solicitud incorrecta
          
  /dispositivos/{codigo}:
    get:
      tags:
        - Dispositivo
      summary: Obtiene el dispositivo correspondiente al codigo
      description: Devuelve el dispositivo correspondiente al codigo especificado
      parameters:
        - name: codigo
          in: path
          description: Código del dispositivo
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Dispositivo correspondiente al codigo especificado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Dispositivo"
        "404":
          description: No se encontró el dispositivo
    put:
      tags:
        - Dispositivo
      summary: Actualiza el dispositivo correspondiente al codigo
      description: Actualiza el dispositivo correspondiente al codigo especificado con la estructura proporcionada y devuelve un booleano para indicar si ha sido correcta la actualización del registro en BD.
      parameters:
        - name: codigo
          in: path
          description: Código del dispositivo
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Estructura que define un dispositivo
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Dispositivo"
      responses:
        "200":
          description: Actualizado exitosamente
        "400":
          description: Solicitud incorrecta
        "404":
          description: No se encontró el dispositivo
    delete:
      tags:
        - Dispositivo
      summary: Elimina el dispositivo correspondiente al codigo
      description: Elimina el dispositivo correspondiente al codigo especificado de BD
      parameters:
        - name: codigo
          in: path
          description: Código del dispositivo
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "204":
          description: Eliminado exitosamente
        "404":
          description: No se encontró el dispositivo

  /notificaciones/presencia:
    post:
      tags:
        - Notificacion
      summary: Notificar presencia en sala
      description: Envía un email a los empleados presentes en una sala indicando el nombre de la sala.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sala:
                  type: string
                  description: Nombre de la sala
              required:
                - sala
      responses:
        '200':
          description: Notificación enviada con éxito
        '400':
          description: Parámetros incorrectos
        '500':
          description: Error interno del servidor
          
  /notificaciones/validacion/{nif}:
    get:
      tags:
        - Notificacion
      summary: Notificar usuario válido
      description: Envía un email a un empleado si es válido
      parameters:
        - in: path
          name: nif
          description: NIF del empleado
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Notificación enviada con éxito
        '400':
          description: Parámetros incorrectos
        '404':
          description: Empleado no encontrado
        '500':
          description: Error interno del servidor
          
  /notificaciones/error:
    post:
      tags:
        - Notificacion
      summary: Notificar error
      description: Envía un email a un empleado de un error
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nif:
                  type: string
                  description: NIF del empleado
                error:
                  type: string
                  description: Descripción del error
              required:
                - nif
                - error
      responses:
        '200':
          description: Notificación enviada con éxito
        '400':
          description: Parámetros incorrectos
        '404':
          description: Empleado no encontrado
        '500':
          description: Error interno del servidor


components:
  schemas:
    Sala:
      type: object
      properties:
        codigoSala:
          type: integer
        nombre:
          type: string
        nivel:
          type: integer
      required:
        - codigoSala
        - nombre
        - nivel
    Nivel:
      type: object
      properties:
        nivel:
          type: integer
        descripcion:
          type: string
      required:
        - nivel
        - descripcion
    Dispositivo:
      type: object
      properties:
        codigo:
          type: integer
        descripcion: 
          type: string
      required:
        - codigo
        - descripcion