/* 
 * Hola Mundo Dtic
 *
 * Esto es un Hola Mundo
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@dtic.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DefaultApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class DefaultApiTests
    {
        private DefaultApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new DefaultApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DefaultApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' DefaultApi
            //Assert.IsInstanceOfType(typeof(DefaultApi), instance, "instance is a DefaultApi");
        }

        /// <summary>
        /// Test HolamundoGet
        /// </summary>
        [Test]
        public void HolamundoGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string nombreHolaMundo = null;
            //var response = instance.HolamundoGet(nombreHolaMundo);
            //Assert.IsInstanceOf<InlineResponse200> (response, "response is InlineResponse200");
        }
        /// <summary>
        /// Test HolamundoPut
        /// </summary>
        [Test]
        public void HolamundoPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string nombreHolaMundo = null;
            //instance.HolamundoPut(nombreHolaMundo);
            
        }
    }

}
